#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../config"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../common-functions"

SERVICE="$1"

if [[ -z "$SERVICE" ]]; then
  dokku_log_fail "Please specify a service name"
fi

if service_exists "$SERVICE"; then
  exit 0
else
  exit 1
fi
