#!/usr/bin/env bash
set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../config"
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../common-functions"

SERVICE="$1"

require_service "$SERVICE"

PLUGIN_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

dokku_log_info1 "Restarting ${PLUGIN_SERVICE} service $SERVICE"

"$PLUGIN_DIR/stop" "$SERVICE"
"$PLUGIN_DIR/start" "$SERVICE"
